// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SplitDto,
} from "./types";

export const params = {
  accountId: __t.string(),
  displayName: __t.string(),
  mapUid: __t.string(),
  checkpointTimes: __t.array(__t.u32()),
  totalTime: __t.u32(),
  runDate: __t.option(__t.timestamp()),
};
export const returnType = SplitDto