// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  accountId: __t.string(),
  displayName: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const Split = __t.object("Split", {
  id: __t.u64(),
  accountId: __t.string(),
  mapUid: __t.string(),
  checkpointTimes: __t.array(__t.u32()),
  totalTime: __t.u32(),
  runDate: __t.timestamp(),
});
export type Split = __Infer<typeof Split>;

export const SplitDto = __t.object("SplitDto", {
  splitId: __t.u64(),
  accountId: __t.string(),
  displayName: __t.string(),
  mapUid: __t.string(),
  checkpointTimes: __t.array(__t.u32()),
  totalTime: __t.u32(),
  runDate: __t.timestamp(),
});
export type SplitDto = __Infer<typeof SplitDto>;

export const TrackMap = __t.object("TrackMap", {
  mapUid: __t.string(),
});
export type TrackMap = __Infer<typeof TrackMap>;

